descriptor-schema-version: "2.2"

info:
  name: ir809_gyro
  description: "Python app to send gyroscope data over mqtt"
  version: "1.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  # Indicate app type (vm, paas, lxc etc.,)
  cpuarch: "x86_64"
  type: docker
  resources:
    profile: default
    network:
      -
        interface-name: eth0

# Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    target: ["/usr/bin/ir809.py"]
